### ISSUE TITLE
更改 title 中的 hexo

### ISSUE THREAD

**Issue by sunBoob** [ochukai/hexo-theme-ochuunn#19]
想更改一下 title 中 文字  比如讲 hexo  更改为我的名字  实现不了

**Comment by ochukai** [comment]
![tim 20170724134922](https://user-images.githubusercontent.com/2998925/28509795-eda2769c-7076-11e7-9794-74da1693481a.png)

title 设置是在上面几个文件设置的，具体你要改哪一个页面的 title 呢？

**Comment by sunBoob** [comment]
thank you 谢谢你  这里我已经解决了，我想改一下css样式。就是目录下边文章的可点击区域，想给大一点，不知道怎么改。
![1501508662 1](https://user-images.githubusercontent.com/30370097/28780488-7987b1b4-7639-11e7-8f8e-f4c82e050785.jpg)

**Comment by ochukai** [comment]
![tim 20170801094927](https://user-images.githubusercontent.com/2998925/28805798-0c8963bc-769f-11e7-8bc1-0c9cdd742eda.png)
