### ISSUE TITLE
主题应用不成功

### ISSUE THREAD

**Issue by Doracool** [ochukai/hexo-theme-ochuunn#2]
我安装之后运行报错这个 是什么原因呢 include _views/post include _views/menu extends _views/index block head title = config.title

**Comment by ochukai** [comment]
没有安装 hexo-renderer-jade, 因为我前端页面用 jade 写的~
```sh
npm install hexo-renderer-jade --save 
```
这样就好了~

**Comment by Doracool** [comment]
谢谢😂  我是先执行的安装jade  然后才添加的package.json   ，然后现在步骤反过来执行了就好了  ~
