### ISSUE TITLE
如何加入照片？以及如何限制页面post的数量

### ISSUE THREAD

**Issue by leewp14** [ochukai/hexo-theme-ochuunn#21]
我在_config.yml 开启了post assets folder 功能，现在是使用`{% asset_img "照片.jpg" %}`来加入照片。有更简单的方法吗？（如，别的theme有的是写`photos:
 -https://xxx.jpg`）
我已设置pagination 在 _config.yml，该生成的pagination的file也在hexo generate时生成了 但首页的post数量还是没有受限制。
谢谢

**Comment by ochukai** [comment]
我的不支持分页哦，默认是全部显示所有的文章标题~

**Comment by ochukai** [comment]
```md
title: Gallery Post
date: 2013-12-25 00:16:18
photos:
- /assets/wallpaper-2572384.jpg
- /assets/wallpaper-2311325.jpg
- /assets/wallpaper-878514.jpg
- http://placehold.it/350x150.jpg
---

This post contains 4 photos:

- Widescreen wallpaper
- Portrait photo
- Dual widescreen wallpaper
- Small photo

All photos should be displayed properly.

*From [Wallbase.cc](http://wallbase.cc)*
```

标题图片的话 这样是支持的~（在我的博客最下面可以看到所有的例子~）

**Comment by leewp14** [comment]
了解 :smile: 谢谢教程！
很喜欢这个theme :smile:

**Comment by ochukai** [comment]
看了一下你的主页，确实 你的内容跟我的主题很搭~ 哈哈哈哈

**Comment by leewp14** [comment]
也奇怪了 您怎么发现我的主页的 我没有publicise在我的profile哦 ._. 今天在publicise罢了xD
