### ISSUE TITLE
我是新手，可能是很简单的问题

### ISSUE THREAD

**Issue by life404** [ochukai/hexo-theme-ochuunn#24]
我在想能不能加上**mathjax公式**，或者说有什么简单的实现方法，望作者告知

**Comment by ochukai** [comment]
刚刚看到，等我找一下

**Comment by ruruozhenhao** [comment]
请问为什么我点击目录后显示的是"Cannot GET /archives",刚开始学习，还望指导 🙇

**Comment by ochukai** [comment]
@ruruozhenhao 一般配置好主题启动 hexo 之后，这些路由都是有的。

当然一定更要确定主题配置的是正确的名称，而且主题文件夹放对了位置，名字也是对的。

如果还是不行的话是不是没有文章，不行就执行 ```hexo clean && hexo s --debug``` 这个再试试咯~

**Comment by Joiey** [comment]
`有个问题打扰一下，部署到服务器上后，显示这个`extends views/index block head title = config.title`
hexo generate, scp把public文件夹上传到服务器的

**Comment by ochukai** [comment]
@Joiey 没有装 jade 吧~  你看 readme 里面的大叹号~

**Comment by Joiey** [comment]
`hexo-renderer-pug`这个安装了，要把NGINX的目录定到public文件夹里面吗 @ochukai

**Comment by ochukai** [comment]
就像我的 deploy 方式是 `git`, hexo 就会自动把 `.deploy_git` 文件夹下面的东西 push 到 git，同理就看你生成的网页部分代码在什么文件夹下面咯。

**Comment by skysunsun** [comment]
> 我在想能不能加上**mathjax公式**，或者说有什么简单的实现方法，望作者告知

me too!! but I'm a fish!!!  How do I change it and let it support mathjax? Thank you very much!!

**Comment by ochukai** [comment]
ok, I will add mathjax support. @skysunsun

**Comment by ochukai** [comment]
@life404 断掉的手重新接上了，所以今天才把 mathjax 加上，还记得我的话 可以试用一下哦~

**Comment by ochukai** [comment]
@skysunsun 可以了~ 多亏了你，否则我就忘记了~

**Comment by ochukai** [comment]
记得看 readme，使用还是比较简单的 毕竟你们都会 **mathjax**~
