### ISSUE TITLE
可以加入Font Awesome吗？

### ISSUE THREAD

**Issue by forestzhang945** [ochukai/hexo-theme-ochuunn#26]
为了更方便使用图标，自己尝试了下，失败了。

**Comment by ochukai** [comment]
我今晚肯定加上否则剁手~

**Comment by ochukai** [comment]
完了 我已经剁手无数次，没有办法写代码了~

**Comment by forestzhang945** [comment]
不用剁手了，我已经解决了
![image](https://user-images.githubusercontent.com/9585063/39344346-6d019568-4a14-11e8-9b81-3e35781dfe1f.png)
