### ISSUE TITLE
自定义方式~

### ISSUE THREAD

**Issue by DragonOnGit** [ochukai/hexo-theme-ochuunn#29]
大佬你这个主题好好看，但是readme里面给的信息太少了QAQ，能不能麻烦再丰富一下自定义的内容呢QAQ

**Comment by ochukai** [comment]
什么是自定义的内容哦~

**Comment by rubychat** [comment]
请问下，可以安装Valine评论系统吗？在哪安装？

**Comment by ochukai** [comment]
@rubychat 这是一个好提议 我更新一下~

**Comment by DragonOnGit** [comment]
> 什么是自定义的内容哦~

就是···一些可以自己修改的···怎么说呢，就某些文字或者样式的修改

**Comment by ochukai** [comment]
@rubychat valine 我支持了，你 pull 一下，设置你的 id 和 key 就好了

**Comment by ochukai** [comment]
@DragonOnGit 你说的也对~ 然后我只把 文章最下面的 copyright 自定义了，这个也太算，说实话，暂时还没想到什么，哈哈~ 方便的话你告诉我~

**Comment by rubychat** [comment]
@ochukai  大佬神速。
还有个问题问一下哦，为什么只要hexo clean /g/d 之后，CNAME文件就要重新创建。是Bug吗？

**Comment by ochukai** [comment]
CNAME 文件你放在什么地方了，是不是被 clean 了~ @DragonOnGit

**Comment by rubychat** [comment]
已解决，谢谢！
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 2019/2/15, 09:51 Oliver Wang <notifications@github.com> wrote:
CNAME 文件你放在什么地方了，是不是被 clean 了~ @DragonOnGit
