### ISSUE TITLE
可以支持Valine的这个分支吗

### ISSUE THREAD

**Issue by xiyuvi** [ochukai/hexo-theme-ochuunn#34]
请问大佬可以支持https://deserts.io/diy-a-comment-system/这个基于Valine的分支吗，相比原版实现了更好的垃圾评论支持 ，以及禁止匿名评论0.0

**Comment by xiyuvi** [comment]
https://deserts.io/diy-a-comment-system/

**Comment by ochukai** [comment]
好哒 马上支持~

**Comment by ochukai** [comment]
这几天太忙没来得及看git

**Comment by ochukai** [comment]
@xiyuvi 好了哦，等下你 pull 试一下，

他把随机头像去掉了，这个我不能忍~我自己 fork 了一份，加上了随意头像，其他的我没有动，他原来的功能保持不变~

**Comment by diannao120** [comment]
123
