### ISSUE TITLE
error

### ISSUE THREAD

**Issue by iXinwei** [ochukai/hexo-theme-ochuunn#36]
> Unhandled rejection TypeError: E:\ryuujo\blog\blog\themes\ochuunn\layout\views\nav.pug:3
>     1| nav.head-nav.u-fr
>     2|   ul.head-nav__list
>   > 3|     each val, index in theme.menu
>     4|       li.head-nav__item: a.head-nav__link(href = url_for(val))
>     5|         = index
> 
> Cannot read property 'length' of undefined
>     at eval (eval at wrap (E:\ryuujo\blog\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:79:33)
>     at template (eval at wrap (E:\ryuujo\blog\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:132:72)
>     at Theme._View.View._compiled.locals [as _compiled] (E:\ryuujo\blog\blog\node_modules\hexo\lib\theme\view.js:125:48)
>     at Theme._View.View.View.render (E:\ryuujo\blog\blog\node_modules\hexo\lib\theme\view.js:30:15)
>     at route.set (E:\ryuujo\blog\blog\node_modules\hexo\lib\hexo\index.js:394:29)
>     at tryCatcher (E:\ryuujo\blog\blog\node_modules\bluebird\js\release\util.js:16:23)
>     at E:\ryuujo\blog\blog\node_modules\bluebird\js\release\method.js:15:34
>     at RouteStream._read (E:\ryuujo\blog\blog\node_modules\hexo\lib\hexo\router.js:134:3)
>     at RouteStream.Readable.read (_stream_readable.js:442:10)
>     at resume_ (_stream_readable.js:822:12)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9)

anything goes wrong?

**Comment by ochukai** [comment]
copy **config.default.yml** to **config.yml** and edit this **config.yml**.

![image](https://user-images.githubusercontent.com/2998925/58771788-99c14d80-85e8-11e9-9a0e-34f155333a26.png)

**Comment by iXinwei** [comment]
thanks a lot!
