### ISSUE TITLE
Tag页“File not found”

### ISSUE THREAD

**Issue by Meowcolm024** [ochukai/hexo-theme-ochuunn#39]
如果是localhost运行点击tags就是```Cannot GET /tags/```
Archive页面正常，点击文章中的标签也正常。。。
[参考链接](https://meltryllis.bitbucket.io)

**Comment by ochukai** [comment]
我检查一下~

**Comment by Meowcolm024** [comment]
自己把问题解决了只要现在terminal里面```hexo new page "tags"```再把```index.md```加上```type: "tags"```就好了
