### ISSUE TITLE
默认情况下好像没有生成tags的index页

### ISSUE THREAD

**Issue by assange0** [ochukai/hexo-theme-ochuunn#40]
直接`hexo g`生成的/tags目录下面似乎缺失index.html，导致nginx之类的有时访问会有403错误。

**Comment by ochukai** [comment]
该怎么关联 issue 39~

**Comment by assange0** [comment]
> 
> 
> 该怎么关联 issue 39~

#39 所以除了手动添加外，可以直接通过主题修复么？

**Comment by ochukai** [comment]
hexo 的目录 **~/source/tags/index.md**

而我们的主题在 **~/themes/ochuunn**

是必须要手动加一下子~
