### ISSUE TITLE
页面问题

### ISSUE THREAD

**Issue by Swiftfrog** [ochukai/hexo-theme-ochuunn#6]
hexo g没问题。
但是hexo s后，访问本地页面，出现：
include _views/post include _views/menu extends _views/index block head title = config.title

这是什么问题，菜鸟一个，希望解答，谢谢。

**Comment by ochukai** [comment]
```sh
npm install hexo-renderer-jade --save
```

这个 在 readme 里面有哦， 安装 jade 就好了~

**Comment by ochukai** [comment]
不好意思不是那个的问题 是因为 jade 的render 更新了，必须使用 pug 了，我改一下提交~

**Comment by ochukai** [comment]
首先在我的主题下面执行 `git pull --rebase`

然后安装 pug~

```sh
npm install hexo-renderer-pug --save
```
这样就好了~

**Comment by Swiftfrog** [comment]
太谢谢了，好的。
主体很棒，很喜欢。加油。

2017-05-15 14:45 GMT+08:00 Oliver Wang <notifications@github.com>:
